Repository justincase-jp/aws-codepipeline-notification-cdk-construct, pull requests merged in 2022-03, with the labels that each got.

#1 feat: ConstructHubに公開できるように
  .editorconfig
  .gitignore
  .projen/deps.json
  .projen/tasks.json
  .projenrc.js
  API.md
  README.md
  lambda/pipeline-notification/app.py
  package.json
  src/index.ts
  src/integ.default.ts
  src/notify-lambda.ts
  test/hello.test.ts
  test/notify-lambda.test.ts
  yarn.lock
Labels: size/XL

#2 chore(projen): metadataとauthorの修正
  .projenrc.js
  package.json
Labels: size/S

#3 fix: notify only `Props` Pipeline only
  .nvmrc
  API.md
  README.md
  src/integ.default.ts
  src/notify-lambda.ts
  test/notify-lambda.test.ts
Labels: size/M
